name: flutter_retrofit_dio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-76.0.dev

dependencies:
  flutter:
    sdk: flutter
  # retrofit
  retrofit: ^4.4.2

  # dio
  dio: ^5.8.0+1

  # logger
  logger: ^2.5.0

  # bloc
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0

  # equatable
  equatable: ^2.0.7

  # dependency injection
  get_it: ^8.0.3

  # routing
  go_router: ^15.1.1

  # json annotation
  json_annotation: ^4.9.0

  # connectivity plus 
  connectivity_plus: ^6.1.4

  # cached network image 
  cached_network_image: ^3.4.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # retrofit generator
  retrofit_generator: ^9.1.9

  # flutter gen runner
  flutter_gen_runner: ^5.10.0


  # build runner
  build_runner: ^2.4.15

  # json serializable
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/jpg/
     


